### ISSUE TITLE
Crash when loading into multiplayer game

### ISSUE THREAD

**Issue by Patrick-van-Halm** [Algalish/SmartIssueTracker#68] opened 2020-11-30 09:34 UTC
When loading into a multiplayer game with the latest version the game crashes.

Smart version: Latest
Satisfactory version: Experimental (137909)

**Log:**
```
Version: 137909, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Epic, NetMode: Client, IsUsingMods: Yes

Unhandled exception

UE4_SmartFoundations_Win64_Shipping
UE4_SmartFoundations_Win64_Shipping
UE4_SmartFoundations_Win64_Shipping
UE4_SmartFoundations_Win64_Shipping
FactoryGame_Win64_Shipping!AActor::DispatchBeginPlay() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\actor.cpp:3395]
FactoryGame_Win64_Shipping!AWorldSettings::NotifyBeginPlay() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\worldsettings.cpp:253]
FactoryGame_Win64_Shipping!AFGWorldSettings::NotifyBeginPlay() [d:\ws\sb-160502110050-fad\ue4\games\factorygame\source\factorygame\private\fgworldsettings.cpp:229]
FactoryGame_Win64_Shipping!AGameStateBase::OnRep_ReplicatedHasBegunPlay() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\gamestatebase.cpp:168]
FactoryGame_Win64_Shipping!UFunction::Invoke() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\uobject\class.cpp:4644]
FactoryGame_Win64_Shipping!UObject::ProcessEvent() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:1464]
FactoryGame_Win64_Shipping!AActor::ProcessEvent() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\actor.cpp:825]
FactoryGame_Win64_Shipping!FRepLayout::CallRepNotifies() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\replayout.cpp:3095]
FactoryGame_Win64_Shipping!FObjectReplicator::CallRepNotifies() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\datareplication.cpp:1695]
FactoryGame_Win64_Shipping!UActorChannel::ProcessBunch() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\datachannel.cpp:2583]
FactoryGame_Win64_Shipping!UActorChannel::ReceivedBunch() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\datachannel.cpp:2408]
FactoryGame_Win64_Shipping!UChannel::ReceivedNextBunch() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\datachannel.cpp:775]
FactoryGame_Win64_Shipping!UChannel::ReceivedRawBunch() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\datachannel.cpp:456]
FactoryGame_Win64_Shipping!UNetConnection::ReceivedPacket() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\netconnection.cpp:2011]
FactoryGame_Win64_Shipping!UNetConnection::ReceivedRawPacket() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\netconnection.cpp:1111]
FactoryGame_Win64_Shipping!UIpNetDriver::TickDispatch() [d:\ws\sb-160502110050-fad\ue4\engine\plugins\online\onlinesubsystemutils\source\onlinesubsystemutils\private\ipnetdriver.cpp:564]
FactoryGame_Win64_Shipping!TBaseUObjectMethodDelegateInstance<0,AFGCharacterPlayer,void __cdecl(float)>::ExecuteIfSafe() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\core\public\delegates\delegateinstancesimpl.h:679]
FactoryGame_Win64_Shipping!TBaseMulticastDelegate<void,float>::Broadcast() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\core\public\delegates\delegatesignatureimpl.inl:977]
FactoryGame_Win64_Shipping!UWorld::Tick() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\leveltick.cpp:1448]
FactoryGame_Win64_Shipping!UGameEngine::Tick() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\gameengine.cpp:1366]
FactoryGame_Win64_Shipping!UFGGameEngine::Tick() [d:\ws\sb-160502110050-fad\ue4\games\factorygame\source\factorygame\private\fggameengine.cpp:9]
FactoryGame_Win64_Shipping!FEngineLoop::Tick() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\launch\private\launchengineloop.cpp:4032]
FactoryGame_Win64_Shipping!GuardedMain() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\launch\private\launch.cpp:168]
FactoryGame_Win64_Shipping!GuardedMainWrapper() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\launch\private\windows\launchwindows.cpp:145]
FactoryGame_Win64_Shipping!WinMain() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\launch\private\windows\launchwindows.cpp:275]
FactoryGame_Win64_Shipping!__scrt_common_main_seh() [d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll
```

**Comment by Algalish** [comment] 2020-11-30 18:56
@Patrick-van-Halm  Hi, just to confirm - you are using Smart! V.10 right?
And does it crash on a client or on a server?

**Comment by Patrick-van-Halm** [comment] 2020-11-30 19:37
> @Patrick-van-Halm Hi, just to confirm - you are using Smart! V.10 right?
> And does it crash on a client or on a server?

Yes V.10 and the client just crashes I get the initialization screen and then it crashes.

**Comment by Algalish** [comment] 2020-11-30 20:54
I assume that it happens 100% of time when you enter multipleyer?
I haven't tested and officially supported this experimental branch.
Can you test it with the EA branch and let me know?
I know that suggesting playing EA is not a solution for you but at least I will get an understanding of what is going on.
Thx

**Comment by Algalish** [comment] 2020-11-30 20:56
@Patrick-van-Halm  if the issue is 100% EXP and there will be no way for you to switch back to EA then I will probably be able to build a special version for you for playing EXP. Will not releasing it like I did with fluids update, since too many people are plating EA and it will break multiplayer for them.

**Comment by Patrick-van-Halm** [comment] 2020-11-30 21:18
> @Patrick-van-Halm if the issue is 100% EXP and there will be no way for you to switch back to EA then I will probably be able to build a special version for you for playing EXP. Will not releasing it like I did with fluids update, since too many people are plating EA and it will break multiplayer for them.

Thats understandable I will take a look tomorrow if the problem also occurs in EA. And tbh if you have to go through the trouble to make a whole new version for EXP imo you wouldn't have to but maybe for the future release since EXP will ofcourse be ported to EA at some point.

**Comment by Algalish** [comment] 2020-11-30 22:17
@Patrick-van-Halm  You are right, I will have to do it at some point, but after last time I had A LOT of people asking me why the mod is not working, so will think carefully before switching to EXP support. So let me think about it and lets find the source of the problem first.

**Comment by Patrick-van-Halm** [comment] 2020-12-01 08:19
Yeah, that's understandable. Experimental is not called Experimental if it didn't come with its flaws. 
Alright so the test results concluded: V.10 of smart does not crash my client on EA branch.

**Comment by Ettychel** [comment] 2020-12-02 17:06
Hey. I am having a 100% crash problem when using this mod in multiplayer when I am a client. I play on the EA branch. Sorry for my English. P.s. Google translator

**Comment by Algalish** [comment] 2020-12-02 17:08
@Ettychel  Hi! Are you using the latest verison of the mod (V10) ?  And can you share some screenshots/logs for that crash?

**Comment by Ettychel** [comment] 2020-12-02 17:47
About a miracle! It finally loaded for me! The game has just been updated to version 138329 and now there are no problems, but the error and symptoms were the same as Patrick-van-Halm. Before that there was a version of the game 138299. Thanks for the quick answer)

**Comment by Algalish** [comment] 2020-12-07 02:25
@Patrick-van-Halm @Ettychel 
I am closing this for now since there are no more reports of that.

**Closed by Algalish** 2020-12-07 02:25 UTC
