### ISSUE TITLE
When movement controls are set to ESDF, can not move forward with "E" while dismantling/building.

### ISSUE THREAD

**Issue by joshp12345** [Algalish/SmartIssueTracker#124] opened 2021-02-21 05:26 UTC
I use ESDF movement controls because I have long fingers. And E is the regular interact key, so something's happening there.

**Comment by dempsey001** [comment] 2021-03-05 20:32
Confirmed. I have this same issue as I use the ESDF to provide more buttons around my main nav keys for all games. The issue seems to be when you have a smart capable item activated on the build tool preparing to build. You can then use the other nav keys but not forward. (I checked using a different forward key and it doesn't work there either. Seems like it is only responding to W)

I validated this using Vanilla and then launched the game with just the SmartMod added.

Steps to Reproduce:

1) I create a quick platform to work on.
2) Create a splitter and set it down (do not close build tool)
3) Attempt to move forward with non-default Forward keybinding. 
4) Notice no forward movement allowed. At this point reverse and lateral movement are still possible.

I also tried toggling various menu options to see if they were linked somehow and didn't notice any difference with things like auto-hold and auto-connect being on/off.

**Comment by Algalish** [comment] 2021-03-05 20:47
@dempsey001 @joshp12345 
E key is reserved for "Elevate" function for Smart!
I can add the ability to turn it off in settings or add the ability to re-map it to another key.

**Comment by dempsey001** [comment] 2021-03-05 22:13
A key remap would be solid fix. I'd hate to lose (or need to disable) the elevate option because of nav keybinds.

**Comment by DarAmetis** [comment] 2021-03-06 10:55
@Algalish 
> I can add the ability to turn it off in settings or add the ability to re-map it to another key.

I don't have a problem as an author, but I'd love to see the key remapping.
I don't like hotkeys on P, T, U - too far. I would like to be able to reassign everything for yourself.

**Comment by Algalish** [comment] 2021-05-15 04:09
Complete remap of all keys is coming at some point, hold on.
E is now L in 16.3.1 so the main problem of that issue is fixed

**Closed by Algalish** 2021-05-15 04:09 UTC
